### ISSUE TITLE
RDF/JS compatibility

### ISSUE THREAD

**Issue by thewilkybarkid** [ontola/ontologies#3]
Looking at the code I can see some mentions of making it compatible with RDF/JS, but just tried it out and unfortunately the types don't seem to be: https://github.com/ontola/ontologies/blob/1cd14fa3ed82ce3cf423d8f243ca16c30fbd12ba/core/src/types.ts#L29-L41 isn't assignable to an [RDF/JS `Quad_Subject`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/260e3f2f9fa84e283bb0e9499ca3945cf7ea6f53/types/rdf-js/index.d.ts#L141-L147) as the local `NamedNode` doesn't contain the `equals()` property of the [RDF/JS `NamedNode`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/260e3f2f9fa84e283bb0e9499ca3945cf7ea6f53/types/rdf-js/index.d.ts#L26-L44).

Is this meant to be compatible, and, if so, could the local types be replaced in favour of using the RDF/JS ones directly?

**Comment by rescribet** [comment]
Hi @thewilkybarkid, thanks for your issue. The included types indeed don't include the `equals` method but rather a plain object representation of only a strict subset, they (the term types) are limited to such a degree that all implementations could trivially provide. I should document these reasons a bit better, but one of the things playing a role is service/web worker compatibility (only plain objects).

The way I've integrated the store into the project which require `equals` is by creating an `rdf.ts` file which exports the proper types and the factory, e.g.

```
import rdf from '@ontologies/core'
export * from '@types/rdf-js' 

export default rdf;
```

The [factory enabled by default](https://github.com/ontola/ontologies/blob/1cd14fa3ed82ce3cf423d8f243ca16c30fbd12ba/core/src/PlainFactory.ts#L89) does have `equals` method support (though I like to use the factory method `rdf.equals(a, b)` since that will work regardless of library) and some functions for rdflib.js compatibility.

Note that each factory ought to [declare what features it has](https://github.com/ontola/ontologies/blob/master/core/src/types.ts#L99) so you can [optimize your code](https://github.com/fletcher91/link-lib/commit/ba90c3438d1887a9efb0537a65db10d44cc5b32a) if the factory has certain characteristics.

**Comment by thewilkybarkid** [comment]
Thanks @fletcher91, I'll close as it's not planned.
